apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: wildfly
  name: wildfly
  namespace: hikingtracks
spec:
  host: wildfly-hikingtracks.7e14.starter-us-west-2.openshiftapps.com
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: wildfly
    weight: 100
  wildcardPolicy: None
